routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\TrackerController;
use App\Http\Controllers\ReporterController;
use App\Http\Controllers\User\UserController;
use App\Http\Controllers\Admin\ActivityController;
use App\Http\Controllers\Admin\AdminReportController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [ReporterController::class, 'create'])->name('reporter.index');
Route::post('/store/reporter', [ReporterController::class, 'store'])->name('reporter.store');

Route::get('/laporan', [ReportController::class, 'create'])->name('laporan.index');
Route::get('/laporan/dashboard', [ReportController::class, 'index'])->name('laporan.dashboard');
Route::post('/store/report', [ReportController::class, 'store'])->name('laporan.store');

Route::get('/admin/login', [UserController::class, 'index'])->name('admin.login');
Route::post('admin/login/auth', [UserController::class, 'login'])->name('admin.store');
Route::get('/admin/register', [UserController::class, 'formRegister'])->name('admin.formRegister');
Route::post('/admin/register/auth', [UserController::class, 'register'])->name('admin.register');
Route::get('/admin/logout', [UserController::class, 'logout'])->name('admin.logout');


Route::middleware(['auth'])->group(function (){

    Route::get('/admin/dashboard', [UserController::class, 'dashboard'])->name('admin.dashboard');
    Route::resource('/admin/report', AdminReportController::class);
    Route::resource('/admin/activity', ActivityController::class);
    Route::resource('/admin/tracker', TrackerController::class);

});

app/Models/Tracker.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Tracker extends Model
{
    use HasFactory;
    protected $fillable = [
        'user_id',
        'report_id',
        'status',
        'note'
    ];

    protected $with = ['user', 'report'];
    

    public function report()
    {
        return $this->belongsTo(Report::class);
    }
    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/TrackerController.php
<?php

namespace App\Http\Controllers;

use App\Models\Report;
use App\Models\Tracker;
use App\Http\Requests\StoreTrackerRequest;
use App\Http\Requests\UpdateTrackerRequest;

class TrackerController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $tracker = Tracker::latest()->get();
        return view('Admin.Tracker.Index', [
            'tracker' => $tracker
        ]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreTrackerRequest $request)
    {
        //
    }

    /**
     * Display the specified resource.
     */
    public function show(Tracker $tracker)
    {
        $tracker = Tracker::where('id', $tracker->id)->first();

        return view('Admin.Tracker.show', [
            'tracker' => $tracker,
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Tracker $tracker)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateTrackerRequest $request, Tracker $tracker)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Tracker $tracker)
    {
        //
    }
}

resources/views/Admin/Tracker/index.blade.php
@extends('layouts.admin')

@section('css')
<link rel="stylesheet" href="https://cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css">
@endsection

@section('title', 'Halaman Report Tracker')

@section('header', 'Report Tracker')

@section('content')
    <table id="tracker" class="table">
        <thead>
            <tr>
                <th>No</th>
                <th>User</th>
                <th>Report</th>
                <th>Status</th>
                <th>Note</th>
                <th>Detail</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($tracker as $key => $value)
            <tr>
                <td>{{ $key += 1 }}</td>
                <td>{{ $value->user_id }}</td>
                <td>{{ $value->report_id }}</td>
                <td>
                    @if ($value->status == 'Pending')
                        <a href="#" class="badge badge-secondary">Pending</a>
                    @elseif ($value->status == 'Proses Administratif')
                        <a href="#" class="badge badge-info">Proses Administratif</a>
                    @elseif ($value->status == 'Proses Penanganan')
                        <a href="#" class="badge badge-warning">Proses Penanganan</a>
                    @elseif ($value->status == 'Selesai Ditangani')
                        <a href="#" class="badge badge-success">Selesai Ditangani</a>
                    @else
                        <a href="#" class="badge badge-danger">Laporan Ditolak</a>
                    @endif
                </td>
                <td class="col-6">{{ Illuminate\Support\Str::limit($value->note, $limit = 200, $end = '...') }}</td>
                <td><a href="{{ route('tracker.show', $value->id) }}" style="text-decoration: underline">Show</a></td>
            </tr>                
            @endforeach
        </tbody>
    </table>
@endsection

@section('js')
<script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>
<script>
    $(document).ready(function() {
        $('#tracker').DataTable();
    });
</script>
@endsection

resources/views/Admin/Tracker/show.blade.php
@extends('layouts.admin')

@section('title', 'Halaman Detail Tracker')

@section('css')
    <style>
        .text-primary:hover {
            text-decoration: underline;
        }

        .text-grey {
            color: #6c757d;
        }

        #gambarZoom {
            width: 200px;
            /* Ukuran awal gambar */
            cursor: pointer;
            /* Ubah kursor saat mengarahkan ke gambar */
        }

        #gambarZoom.zoomed {
            width: 400px;
            /* Ukuran gambar saat di-zoom */
            transition: width 0.3s;
            /* Animasi perubahan ukuran */
        }

        .btn-purple {
            background: #0cb8a7;
            border: 1px solid;
            color: #fff;
            width: 100%;
        }
    </style>
@endsection

@section('header')
    <a href="/admin/tracker" class="text-success">Kembali </a>
    <a href="#" class="text-grey"></a>
    <a href="#" class="text-grey">Report Tracker</a>
@endsection

@section('content')
    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-header">
                    <div class="text-center">
                        Pengaduan Sederhana
                    </div>
                </div>
                <div class="card-body">
                    <table class="table">
                        <tbody>
                            <tr>
                                <th>Tanggal Pengaduan di Update</th>
                                <td>:</td>
                                <td>{{ $tracker->updated_at }}</td>
                            </tr>
                            <tr>
                                <th>Nama Admin</th>
                                <td>:</td>
                                <td>{{ $tracker->user->name }}</td>
                            </tr>
                            <tr>
                                <th>Judul</th>
                                <td>:</td>
                                <td>{{ $tracker->report->title }}</td>
                            </tr>
                            <tr>
                                <th>Status</th>
                                <td>:</td>
                                <td>
                                    @if ($tracker->status == 'Pending')
                                        <a href="#" class="badge badge-secondary">Pending</a>
                                    @elseif ($tracker->status == 'Proses Administratif')
                                        <a href="#" class="badge badge-info">Proses Administratif</a>
                                    @elseif ($tracker->status == 'Proses Penanganan')
                                        <a href="#" class="badge badge-warning">Proses Penanganan</a>
                                    @elseif ($tracker->status == 'Selesai Ditangani')
                                        <a href="#" class="badge badge-success">Selesai Ditangani</a>
                                    @else
                                        <a href="#" class="badge badge-danger">Laporan Ditolak</a>
                                    @endif
                                </td>
                            </tr>
                            <tr>
                                <th>Note</th>
                                <td>:</td>
                                <td>{{ $tracker->note }}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection