routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\TrackerController;
use App\Http\Controllers\ReporterController;
use App\Http\Controllers\User\UserController;
use App\Http\Controllers\Admin\ActivityController;
use App\Http\Controllers\Admin\AdminReportController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [ReporterController::class, 'create'])->name('reporter.index');
Route::post('/store/reporter', [ReporterController::class, 'store'])->name('reporter.store');

Route::get('/laporan', [ReportController::class, 'create'])->name('laporan.index');
Route::get('/laporan/dashboard', [ReportController::class, 'index'])->name('laporan.dashboard');
Route::post('/store/report', [ReportController::class, 'store'])->name('laporan.store');

Route::get('/admin/login', [UserController::class, 'index'])->name('admin.login');
Route::post('admin/login/auth', [UserController::class, 'login'])->name('admin.store');
Route::get('/admin/register', [UserController::class, 'formRegister'])->name('admin.formRegister');
Route::post('/admin/register/auth', [UserController::class, 'register'])->name('admin.register');
Route::get('/admin/logout', [UserController::class, 'logout'])->name('admin.logout');


Route::middleware(['auth'])->group(function (){

    Route::get('/admin/dashboard', [UserController::class, 'dashboard'])->name('admin.dashboard');
    Route::resource('/admin/report', AdminReportController::class);
    Route::resource('/admin/activity', ActivityController::class);
    Route::resource('/admin/tracker', TrackerController::class);

});

app/Models/Report.php
<?php

namespace App\Models;

use App\Models\Reporter;
use Spatie\MediaLibrary\HasMedia;
use Spatie\Activitylog\LogOptions;
use Illuminate\Database\Eloquent\Model;
use Spatie\MediaLibrary\InteractsWithMedia;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Spatie\Activitylog\Traits\LogsActivity;

class Report extends Model implements HasMedia
{
    use HasFactory,InteractsWithMedia, LogsActivity;

    protected $fillable = [

        'reporter_id',
        'category_id',
        'ticket_id',
        'title',
        'description',
        'status',

    ];
    protected $with = ['reporter', 'category'];

    public function getActivitylogOptions(): LogOptions
    {
        return LogOptions::defaults()
            ->logFillable('*');
            // ->setDescriptionForEvent(fn (string $eventName) => "This model has been {$eventName}")
            // ->useLogName('Tracker');
    }

    public function reporter()
    {
        return $this->belongsTo(Reporter::class);
    }
    public function category()
    {
        return $this->belongsTo(Category::class, 'category_id');
    }
    public function tracker()
    {
        return $this->hasMany(Tracker::class);
    }
}

app/Http/Controllers/ReportController.php
<?php

namespace App\Http\Controllers;

use DateTime;
use App\Models\Report;
use Illuminate\Support\Str;
use Illuminate\Http\Request;
use Spatie\Activitylog\Models\Activity;
use Yajra\DataTables\Facades\DataTables;
use Illuminate\Support\Facades\Validator;
use App\Http\Requests\UpdateReportRequest;

class ReportController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        if (request()->ajax()) {
            $reports = Report::query();
            return DataTables::of($reports)
                ->addIndexColumn()
                ->addColumn('action', function ($item) {
                    $button =   '<div class="dropdown">
                                <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Action
                                </button>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" href="#">Edit</a></li>
                                    <li><a class="dropdown-item" href="#">Delete</a></li>
                                </ul>
                            </div> ';
                    return $button;
                })
                ->addColumn('reporter_name', function ($report) {
                    return $report->reporter->name;
                })
                ->addColumn('category_name', function ($report) {
                    return
                        optional($report->category)->name;
                })
                ->editColumn('title', function ($item) {
                    return Str::limit($item->title, 25, '...');
                })
                ->editColumn('reporter_name', function ($report) {
                    return Str::limit($report->reporter->name, 30, '...');
                })
                ->make();
        }
        return view('user.dashboard_laporan');
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('user.laporan',[
            "report" => Report::latest()->get()
        ]);
        // $report = Report::find(1)->getFirstMedia('images')->getUrl();
        // dd($report);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $data = $request->all();

        Validator::make($data, [
            'description' => ['required'],
        ]);

        date_default_timezone_set('Asia/Bangkok');

        $date = new DateTime('now');
        $number = 0;
        $ticket_id = $date->format('Ymd') . str_pad($number + 1, 6, "0", STR_PAD_LEFT);

        $report = Report::create([
            'reporter_id' => $data['reporter_id'],
            'ticket_id' => $ticket_id,
            'title' => $data['title'],
            'description' => $data['description'],
            'status' => 'Pending',
        ]);
        $report->addMediaFromRequest('image')->toMediaCollection('images');

        if ($report) {
            return redirect()->route('reporter.index')->with(['pengaduan' => 'Pengaduan Berhasil terkirim!', 'type' => 'success']);
        } else {
            return redirect()->back()->with(['pengaduan' => 'Pengaduan Gagal terkirim!', 'type' => 'danger']);
        }
    }


    /**
     * Display the specified resource.
     */
    public function show(Report $report)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Report $report)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateReportRequest $request, Report $report)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Report $report)
    {
        //
    }

}

resources/views/Admin/Report/edit.blade.php
@extends('layouts.admin')

@section('title', 'Halaman Activity Log')

@section('header', 'Activity Log')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">
                        Activity Log
                    </div>
                    <div class="card-body">
                        <div class="accordion" id="accordionExample">
                            @forelse ($logs as $key => $log)
                                <div class="accordion-item">
                                    <h2 class="accordion-header">
                                        <button class="accordion-button {{ $key != 0 ? 'collapsed' : '' }}" type="button"
                                            data-bs-toggle="collapse" data-bs-target="#collapse-{{ $key }}"
                                            aria-expanded="true" aria-controls="collapse-{{ $key }}">
                                            <span>{{ $log->description }}</span> <small
                                                class="text-muted ms-2 pb-1">({{ $log->created_at->diffForHumans() }})</small>
                                        </button>
                                    </h2>
                                    <div id="collapse-{{ $key }}"
                                        class="accordion-collapse collapse {{ $key == 0 ? 'show' : '' }}"
                                        data-bs-parent="#accordionExample">
                                        <div class="accordion-body">
                                            <ul class="list-group">
                                                <li class="list-group-item bg-success text-white">Old Data</li>
                                                @if (isset($log['properties']['old']))
                                                    <li class="list-group-item"><strong>Status:</strong>
                                                        {{ $log['properties']['old']['status'] }}</li>
                                                    {{-- <li class="list-group-item"><strong>Note:</strong> {{ $log['properties']['old']['note'] }}</li> --}}
                                                @else
                                                    <li class="list-group-item">No old data available</li>
                                                @endif

                                                <li class="list-group-item bg-success text-white">New Data</li>
                                                @if (isset($log['properties']['attributes']))
                                                    <li class="list-group-item"><strong>Status:</strong>
                                                        {{ $log['properties']['attributes']['status'] }}</li>
                                                    {{-- <li class="list-group-item"><strong>Note:</strong> {{ $log['properties']['attributes']['note'] }}</li> --}}
                                                @else
                                                    <li class="list-group-item">No new data available</li>
                                                @endif
                                            </ul>



                                            {{ $log->description }}

                                        </div>
                                    </div>
                                </div>
                            @empty
                                <div class="accordion-item">
                                    <h2 class="accordion-header">
                                        <button class="accordion-button" type="button" data-bs-toggle="collapse"
                                            data-bs-target="#collapse-{{ $key }}" aria-expanded="true"
                                            aria-controls="collapse-{{ $key }}">
                                            No activity found.
                                        </button>
                                    </h2>
                                </div>
                            @endforelse
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/Admin/Report/index.blade.php
@extends('layouts.admin')

@section('css')
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css">
@endsection

@section('title', 'Halaman Report')

@section('header', 'Report Tracker')

@section('content')
    <div>
        <table id="tracker" class="table">
            <thead>
                <tr>
                    <th>No</th>
                    <th>Reporter Name</th>
                    <th>Category</th>
                    <th>Ticket </th>
                    <th>Title</th>
                    <th>Description</th>
                    <th>Status</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($report as $key => $value)
                    <tr>
                        <td>{{ $key += 1 }}</td>
                        <td>{{ $value->reporter->name }}</td>
                        <td>{{ $value->category?->name }}</td>
                        <td>{{ $value->ticket_id }}</td>
                        <td>{{ $value->title }}</td>
                        <td class="col-4">
                            {{ Illuminate\Support\Str::limit($value->description, $limit = 40, $end = '...') }}</td>
                        <td>
                            @if ($value->status == 'Pending')
                                <a href="#" class="badge badge-secondary">Pending</a>
                            @elseif ($value->status == 'Proses Administratif')
                                <a href="#" class="badge badge-info">Proses Administratif</a>
                            @elseif ($value->status == 'Proses Penanganan')
                                <a href="#" class="badge badge-warning">Proses Penanganan</a>
                            @elseif ($value->status == 'Selesai Ditangani')
                                <a href="#" class="badge badge-success">Selesai Ditangani</a>
                            @else
                                <a href="#" class="badge badge-danger">Laporan Ditolak</a>
                            @endif
                        </td>
                        <td>
                            <div class="btn-group dropstart">
                                <button type="button" class="btn btn-sm btn-outline-success dropdown-toggle" data-bs-toggle="dropdown"
                                    aria-expanded="false">
                                    Action
                                </button>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" href="{{ route('report.show', $value->id) }}">Show & Update</a></li>
                                    <li>
                                        <hr class="dropdown-divider">
                                    </li>
                                    <li><a class="dropdown-item" href="{{ route('report.edit', $value->id) }}">Activity Log</a></li>
                                </ul>
                            </div>

                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @endsection

    @section('js')
        <script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>
        <script>
            $(document).ready(function() {
                $('#tracker').DataTable();
            });
        </script>
    @endsection

resources/views/Admin/Report/show.blade.php
@extends('layouts.admin')

@section('title', 'Halaman Detail Report')

@section('css')
    <style>
        .text-primary:hover {
            text-decoration: underline;
        }

        .text-grey {
            color: #6c757d;
        }

        #gambarZoom {
            width: 200px;
            /* Ukuran awal gambar */
            cursor: pointer;
            /* Ubah kursor saat mengarahkan ke gambar */
        }

        #gambarZoom.zoomed {
            width: 400px;
            /* Ukuran gambar saat di-zoom */
            transition: width 0.3s;
            /* Animasi perubahan ukuran */
        }

        .btn-purple {
            background: #0cb8a7;
            border: 1px solid;
            color: #fff;
            width: 100%;
        }
    </style>
@endsection

@section('header')
    <a href="/admin/report" class="text-success">Kembali </a>
    <a href="#" class="text-grey"></a>
    <a href="#" class="text-grey">Report</a>
@endsection

@section('content')
    <div class="row">
        <div class="col-lg-6 col-12">
            <div class="card">
                <div class="card-header">
                    <div class="text-center">
                        Pengaduan Sederhana
                    </div>
                </div>
                <div class="card-body">
                    <table class="table">
                        <tbody>
                            <tr>
                                <th>Tanggal Pengaduan</th>
                                <td>:</td>
                                <td>{{ $report->created_at }}</td>
                            </tr>
                            <tr>
                                <th>Nama Reporter</th>
                                <td>:</td>
                                <td>{{ $report->reporter->name }}</td>
                            </tr>
                            <tr>
                                <th>Category</th>
                                <td>:</td>
                                <td>{{ $report->category?->name }}</td>
                            </tr>
                            <tr>
                                <th>No Ticket</th>
                                <td>:</td>
                                <td>{{ $report->ticket_id }}</td>
                            </tr>
                            <tr>
                                <th>Judul</th>
                                <td>:</td>
                                <td>{{ $report->title }}</td>
                            </tr>
                            <tr>
                                <th>Description</th>
                                <td>:</td>
                                <td>{{ $report->description }}</td>
                            </tr>
                            <tr>
                                <th>Status</th>
                                <td>:</td>
                                <td>
                                    @if ($report->status == 'Pending')
                                        <a href="#" class="badge badge-secondary">Pending</a>
                                    @elseif ($report->status == 'Proses Administratif')
                                        <a href="#" class="badge badge-info">Proses Administratif</a>
                                    @elseif ($report->status == 'Proses Penanganan')
                                        <a href="#" class="badge badge-warning">Proses Penanganan</a>
                                    @elseif ($report->status == 'Selesai Ditangani')
                                        <a href="#" class="badge badge-success">Selesai Ditangani</a>
                                    @else
                                        <a href="#" class="badge badge-danger">Laporan Ditolak</a>
                                    @endif
                                </td>
                            </tr>
                            <tr>
                                <th>Media</th>
                                <td>:</td>
                                <td>



                                    <img id="gambarZoom" src="{{ $report->getFirstMediaUrl('images') }}" alt="PESAN"
                                        class="img-fluid img-thumbnail" width="200px">


                                </td>
                            </tr>

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-6 col-12">
            <div class="card">
                <div class="card-header">
                    <div class="text-center">
                        Tanggapan
                    </div>
                </div>
                <div class="card-body">
                    <form action="{{ $report->id }}" method="POST">
                        @method('PUT')
                        @csrf
                        <input type="hidden" name="report_id" value={{ $report->id }}>
                        <div class="form-group">
                            <label for="category">Category</label>
                            <div class="input-group mb-3">
                                <select name="category_id" id="category" class="custom-select">
                                    @foreach ($category as $category)
                                        @if ($report->category_id == $category->id)
                                            <option value="{{ $report->category_id }}" selected>{{ $category->name }}</option>
                                        @else
                                            <option value="{{ $category->id }}">{{ $category->name }}</option>
                                        @endif
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="status">Status</label>
                            <div class="input-group mb-3">
                                <select name="status" id="status" class="custom-select">
                                    @if ($report->status == 'Pending')
                                        <option selected value="Pending">Pending</option>
                                        <option value="Proses Administratif">Proses Administratif</option>
                                        <option value="Proses Penanganan">Proses Penanganan</option>
                                        <option value="Selesai Ditangani">Selesai Ditangani</option>
                                        <option value="Laporan Ditolak">Laporan Ditolak</option>
                                    @elseif ($report->status == 'Proses Administratif')
                                        <option value="Pending">Pending</option>
                                        <option selected value="Proses Administratif">Proses Administratif</option>
                                        <option value="Proses Penanganan">Proses Penanganan</option>
                                        <option value="Selesai Ditangani">Selesai Ditangani</option>
                                        <option value="Laporan Ditolak">Laporan Ditolak</option>
                                    @elseif ($report->status == 'Proses Penanganan')
                                        <option value="Pending">Pending</option>
                                        <option value="Proses Administratif">Proses Administratif</option>
                                        <option selected value="Proses Penanganan">Proses Penanganan</option>
                                        <option value="Selesai Ditangani">Selesai Ditangani</option>
                                        <option value="Laporan Ditolak">Laporan Ditolak</option>
                                    @elseif ($report->status == 'Selesai Ditangani')
                                        <option value="Pending">Pending</option>
                                        <option value="Proses Administratif">Proses Administratif</option>
                                        <option value="Proses Penanganan">Proses Penanganan</option>
                                        <option selected value="Selesai Ditangani">Selesai Ditangani</option>
                                        <option value="Laporan Ditolak">Laporan Ditolak</option>
                                    @else
                                        <option value="Pending">Pending</option>
                                        <option value="Proses Administratif">Proses Administratif</option>
                                        <option value="Proses Penanganan">Proses Penanganan</option>
                                        <option value="Selesai Ditangani">Selesai Ditangani</option>
                                        <option selected value="Laporan Ditolak">Laporan Ditolak</option>
                                    @endif

                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="note">Note</label>
                            <textarea name="note" id="note" rows="4" class="form-control" placeholder="Masukkan note"></textarea>
                        </div>
                        <button type="submit" class="btn btn-purple">Submit</button>
                    </form>
                    @if (Session::has('status'))
                        <div class="alert alert-success mt-2">
                            {{ Session::get('status') }}
                        </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
@endsection

@section('js')
    <script>
        document.getElementById('gambarZoom').addEventListener('click', function() {
            this.classList.toggle('zoomed'); // Menambah atau menghapus kelas CSS 'zoomed'
        });
    </script>


@endsection